# Prometheus Configuration for IEClub

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ieclub-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # ========================================
  # Prometheus 自身监控
  # ========================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ========================================
  # Node.js 后端监控
  # ========================================
  - job_name: 'ieclub-backend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['backend:3000']
        labels:
          service: 'backend'
          app: 'ieclub'
    
    # 健康检查
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: backend:3000

  # ========================================
  # MySQL 数据库监控
  # ========================================
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          service: 'mysql'
          app: 'ieclub'

  # ========================================
  # Redis 缓存监控
  # ========================================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          app: 'ieclub'

  # ========================================
  # Nginx 监控
  # ========================================
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          app: 'ieclub'

  # ========================================
  # Node Exporter (系统指标)
  # ========================================
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          app: 'ieclub'

  # ========================================
  # cAdvisor (容器监控)
  # ========================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          app: 'ieclub'

