// Mock数据用于本地开发

export const mockUsers = [
  {
    id: '1',
    nickname: '张三',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=1',
    bio: '热爱技术，专注前端开发',
    skills: ['React', 'TypeScript', 'Node.js'],
    interests: ['AI', '开源', '创业'],
    city: '深圳',
    level: 5,
    points: 1280,
  },
  {
    id: '2',
    nickname: 'Alice',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=2',
    bio: '产品经理，关注用户体验',
    skills: ['产品设计', 'Axure', 'Figma'],
    interests: ['设计', '心理学', '商业'],
    city: '北京',
    level: 4,
    points: 890,
  },
  {
    id: '3',
    nickname: '李华',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=3',
    bio: '数据科学家，机器学习爱好者',
    skills: ['Python', 'TensorFlow', 'SQL'],
    interests: ['机器学习', '数据分析', '量化投资'],
    city: '上海',
    level: 6,
    points: 2340,
  },
];

export const mockTopics = [
  {
    id: '1',
    title: '寻找前端开发合作伙伴，一起开发AI应用',
    content: '我有一个AI创意项目想做，需要前端开发的小伙伴加入。项目是一个智能写作助手，已经有后端和AI模型，现在需要优秀的前端界面。如果你对AI感兴趣，欢迎联系！',
    contentType: 'text',
    category: '技术',
    tags: ['AI', '前端', 'React', '创业'],
    topicType: 'demand',
    demandType: '人员',
    author: mockUsers[0],
    images: [],
    createdAt: new Date('2025-01-15T10:30:00'),
    viewsCount: 234,
    likesCount: 45,
    commentsCount: 12,
    bookmarksCount: 8,
    hotScore: 892,
    _count: {
      likes: 45,
      comments: 12,
      bookmarks: 8,
    },
  },
  {
    id: '2',
    title: '分享一个超好用的代码片段管理工具',
    content: '最近发现了一个宝藏工具 - SnippetBox，可以帮你管理各种代码片段，支持多语言高亮、标签分类、全文搜索。强烈推荐给大家！\n\n主要特性：\n- 支持30+编程语言\n- 云同步\n- VSCode插件\n- 完全免费开源',
    contentType: 'markdown',
    category: '技术',
    tags: ['工具', '开发', '效率'],
    topicType: 'discussion',
    author: mockUsers[1],
    images: ['https://picsum.photos/800/400?random=1'],
    createdAt: new Date('2025-01-14T15:20:00'),
    viewsCount: 567,
    likesCount: 89,
    commentsCount: 23,
    bookmarksCount: 34,
    hotScore: 1245,
    _count: {
      likes: 89,
      comments: 23,
      bookmarks: 34,
    },
  },
  {
    id: '3',
    title: '求推荐深圳靠谱的Python培训机构',
    content: '想学Python做数据分析，有没有在深圳报过培训班的朋友？求推荐靠谱的机构，最好是小班教学的那种。预算1-2万。',
    contentType: 'text',
    category: '学习',
    tags: ['Python', '培训', '深圳'],
    topicType: 'question',
    author: mockUsers[2],
    images: [],
    createdAt: new Date('2025-01-13T09:15:00'),
    viewsCount: 156,
    likesCount: 12,
    commentsCount: 8,
    bookmarksCount: 3,
    hotScore: 345,
    _count: {
      likes: 12,
      comments: 8,
      bookmarks: 3,
    },
  },
];

export const mockComments = [
  {
    id: '1',
    topicId: '1',
    author: mockUsers[1],
    content: '我对这个项目很感兴趣！我有3年React开发经验，可以加个微信详聊吗？',
    createdAt: new Date('2025-01-15T11:30:00'),
    likesCount: 5,
    repliesCount: 1,
    replies: [
      {
        id: '1-1',
        author: mockUsers[0],
        content: '太好了！我的微信是 zhangsan_dev，加我吧',
        createdAt: new Date('2025-01-15T11:45:00'),
        likesCount: 2,
      },
    ],
  },
  {
    id: '2',
    topicId: '1',
    author: mockUsers[2],
    content: '项目技术栈是什么？用的哪个AI模型？',
    createdAt: new Date('2025-01-15T12:00:00'),
    likesCount: 3,
    repliesCount: 0,
  },
];

export const mockNotifications = [
  {
    id: '1',
    type: 'like',
    sender: mockUsers[1],
    content: '赞了你的话题',
    targetTitle: '寻找前端开发合作伙伴',
    isRead: false,
    createdAt: new Date('2025-01-15T14:30:00'),
  },
  {
    id: '2',
    type: 'comment',
    sender: mockUsers[2],
    content: '评论了你的话题',
    targetTitle: '寻找前端开发合作伙伴',
    isRead: false,
    createdAt: new Date('2025-01-15T12:00:00'),
  },
  {
    id: '3',
    type: 'follow',
    sender: mockUsers[0],
    content: '关注了你',
    isRead: true,
    createdAt: new Date('2025-01-14T10:00:00'),
  },
  {
    id: '4',
    type: 'system',
    content: '欢迎加入IEclub！快去发布你的第一个话题吧',
    isRead: true,
    createdAt: new Date('2025-01-13T08:00:00'),
  },
];