version: '3.8'

services:
  # MySQL 测试数据库
  mysql-test:
    image: mysql:8.0
    container_name: ieclub_mysql_test
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: ieclub_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    networks:
      - ieclub_test_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tmpfs:
      - /var/lib/mysql

  # Redis 测试缓存
  redis-test:
    image: redis:7-alpine
    container_name: ieclub_redis_test
    restart: no
    ports:
      - "6380:6379"
    networks:
      - ieclub_test_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10
    tmpfs:
      - /data

volumes:
  mysql_test_data:
    driver: local

networks:
  ieclub_test_network:
    driver: bridge